Web/Web/Controllers/Api/FlowTemplateController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web.Http;
using Flow.Library.Data;
using Flow.Library.Data.Abstract;
using Flow.Library.Steps;
using Flow.Library.Validation;
using Flow.Web.Dto;
using Web;
using FlowTemplate = Flow.Library.Core.FlowTemplate;

namespace Flow.Web.Controllers.Api
{
    public class FlowTemplateController : ApiController
    {
        private readonly IUnitOfWork _unitOfWork;
        private readonly FlowTemplateService _flowTemplateService;

        public FlowTemplateController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
            _flowTemplateService = new FlowTemplateService();
        }

        ~FlowTemplateController()
        {
            Dispose(false);
        }

        [NullResponseIs404]
        public FlowTemplateDto Get(int id)
        {
            var flow = _flowTemplateService.GetFlowTemplate(_unitOfWork, id);
            if (flow == null)
                return null;

            var mappedDtoFlowTemplate = AutoMapper.Mapper.Map<FlowTemplateDto>(flow);
            return mappedDtoFlowTemplate;
        }

        public int Post(FlowTemplateDto flowTemplateDto)
        {
            var steps = new List<IStep>();
            if (flowTemplateDto.Steps != null && flowTemplateDto.Steps.Any())
            {
                steps = flowTemplateDto.Steps.Select(Map).ToList();
            }

            var template = new FlowTemplate
            {
                Id = flowTemplateDto.Id,
                Name = flowTemplateDto.Name,
                Steps = steps
            };

            var id = _flowTemplateService.Add(_unitOfWork, template);
            return id;
        }

        protected static IStep Map(FlowTemplateStepDto dto)
        {
            switch (dto.StepTypeName)
            {
                case "StartStep":
                    return AutoMapper.Mapper.Map<StartStep>(dto);
                case "StopStep":
                    return AutoMapper.Mapper.Map<StopStep>(dto);
                case "CollectDataStep":
                    return AutoMapper.Mapper.Map<CollectDataStep>(dto);
                case "StoreDataStep":
                    return AutoMapper.Mapper.Map<StoreDataStep>(dto);
            }
            throw new NotSupportedException("Unsupported Step StepTypeName provided");
        }

        public void Put(FlowTemplateDto flowTemplateDto)
        {

            var steps = new List<IStep>();
            if (flowTemplateDto.Steps != null && flowTemplateDto.Steps.Any())
            {
                //steps = flowTemplateDto.Steps.Select(Map).ToList();
                foreach (var step in flowTemplateDto.Steps)
                {
                    var mappedStep = Map(step);
                    if (step.Id > 0)
                    {
                        var match = _unitOfWork.FlowTemplateSteps.Get(mappedStep.Id);
                        if (match == null)
                        {
                            throw new ValidationException(String.Format("Step with Id {0} does not exist. Cannot update step.", step.Id));
                        }
                        mappedStep.IsDirty = true;
                    }
                    steps.Add(mappedStep);
                }
            }

            var templateResult = new FlowTemplate
            {
                Id = flowTemplateDto.Id,
                Name = flowTemplateDto.Name,
                Steps = steps,
            };

            _flowTemplateService.Update(_unitOfWork, templateResult);
        }

        public void Delete(int id)
        {
            if(_unitOfWork.FlowTemplates.Get(id) == null)
                throw new HttpResponseException(HttpStatusCode.NotFound);

            _flowTemplateService.Delete(_unitOfWork, new FlowTemplate { Id = id });
        }

        public IEnumerable<FlowTemplateDto> Get()
        {
            var flowTemplates = _flowTemplateService.GetFlowTemplates(_unitOfWork).ToList();
            var mapped = flowTemplates.Select(AutoMapper.Mapper.Map<FlowTemplateDto>).ToList();
            return mapped;
        }

    }
}

Web/Web/Controllers/Api/FlowTemplatesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Caching;
using System.Web.Http;
using System.Web.Mvc;
using Flow.Library.Data;
using Flow.Library.Data.Abstract;
using Flow.Library.Steps;
using Flow.Library.Validation;
using Flow.Web.Dto;
using FlowTemplate = Flow.Library.Core.FlowTemplate;

namespace Flow.Web.Controllers.Api
{
    public class FlowTemplatesController : ApiController
    {
        private readonly IFlowTemplateService _templates;

        public FlowTemplatesController(IFlowTemplateService flowTemplateService)
        {
            _templates = flowTemplateService;
        }

        public IEnumerable<FlowTemplateDto> Get()
        {
            var flowTemplates = _templates.GetFlowTemplates().ToList();
            var mapped = flowTemplates.Select(Map<FlowTemplateDto>).ToList();
            return mapped;
        }

        [NullResponseIs404]
        public FlowTemplateDto Get(int id)
        {
            var flowTemplate = _templates.GetFlowTemplate(id);
            if (flowTemplate == null)
                return null;

            var flowTemplateDto = Map<FlowTemplateDto>(flowTemplate);
            return flowTemplateDto;
        }

        public HttpResponseMessage Post(FlowTemplateDto source)
        {
            var flowTemplate = Map<FlowTemplate>(source);

            if (source.Steps != null && source.Steps.Any())
            {
                flowTemplate.Steps = source.Steps.Select(Map<IStep>).ToList();
            }

            var id = _templates.Add(flowTemplate);
            return Request.CreateResponse(HttpStatusCode.Created, new {Id = id});
        }

        public HttpResponseMessage Put(FlowTemplateDto source)
        {
            if (_templates.GetFlowTemplate(source.Id) == null)
                throw new HttpResponseException(HttpStatusCode.NotFound);

            try
            {
                var flowTemplate = Map<FlowTemplate>(source);
                _templates.Update(flowTemplate);
                return Request.CreateResponse(HttpStatusCode.OK);
            }
            catch (ValidationException validationException)
            {
                return Request.CreateErrorResponse(HttpStatusCode.BadRequest, validationException.Message);
            }
        }

        public HttpStatusCodeResult Delete(int id)
        {
            if(_templates.GetFlowTemplate(id) == null)
                throw new HttpResponseException(HttpStatusCode.NotFound);

            _templates.Delete(new FlowTemplate { Id = id });
            return new HttpStatusCodeResult(HttpStatusCode.OK);
        }

        protected static T Map<T>(object source)
        {
            try
            {
                return AutoMapper.Mapper.Map<T>(source);
            }
            catch (AutoMapper.AutoMapperMappingException ex)
            {
                throw new NotSupportedException("Step is unknown", ex);
            }
        }

    }
}

Web/Web/Controllers/FlowTemplateController.cs
using System.Data.SqlClient;
using System.Web.Mvc;
using AutoMapper;
using Flow.Library.Data;
using Flow.Library.Data.Abstract;
using Flow.Web.Models;

namespace Flow.Web.Controllers
{
    public class FlowTemplateController : Controller
    {
        private readonly IFlowTemplateService _flowTemplateService;
        private readonly IUnitOfWork _unitOfWork;
        private readonly SqlConnection _connection;
        private const string ConnectionString = @"Data Source=.\SQLEXPRESS;Initial Catalog=Flow;Integrated Security=True";

        public FlowTemplateController()
        {
            _connection = new SqlConnection(ConnectionString);
            _connection.Open();
            _unitOfWork = new SqlUnitOfWork(_connection);
            _flowTemplateService =  new FlowTemplateService();
        }

        protected override void Dispose(bool disposing)
        {
            base.Dispose(disposing);
            if (_connection != null)
            {
                _connection.Dispose();
            }
        }

        ~FlowTemplateController()
        {
            Dispose(false);
        }

        public ActionResult Index()
        {
            var model = new FlowTemplateIndexViewModel();
            model.Templates = _flowTemplateService.GetFlowTemplates(_unitOfWork);
            return View(model);
        }

        [HttpGet]
        public ActionResult Add()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Add(global::Flow.Web.Dto.FlowTemplateDto templateDto)
        {
            var flowTemplate = Mapper.Map<Flow.Library.Core.FlowTemplate>(templateDto);
            var id = _flowTemplateService.Add(_unitOfWork, flowTemplate);
            return RedirectToAction("Index", "FlowTemplateController", new {Success = true, Id = id});
        }

    }
}

Web/Web/Controllers/FlowTemplatesController.cs
using System.Data.SqlClient;
using System.Web.Mvc;
using AutoMapper;
using Flow.Library.Data;
using Flow.Library.Data.Abstract;
using Flow.Web.Models;

namespace Flow.Web.Controllers
{
    public class FlowTemplatesController : Controller
    {
        private readonly IFlowTemplateService _flowTemplateService;
        private readonly IUnitOfWork _unitOfWork;
        private readonly SqlConnection _connection;
        private const string ConnectionString = @"Data Source=.\SQLEXPRESS;Initial Catalog=Flow;Integrated Security=True";

        public FlowTemplatesController()
        {
            _connection = new SqlConnection(ConnectionString);
            _connection.Open();
            _unitOfWork = new SqlUnitOfWork(_connection);
            _flowTemplateService = new FlowTemplateService(_unitOfWork);
        }

        protected override void Dispose(bool disposing)
        {
            base.Dispose(disposing);
            if (_connection != null)
            {
                _connection.Dispose();
            }
        }

        ~FlowTemplatesController()
        {
            Dispose(false);
        }

        public ActionResult Index()
        {
            var model = new FlowTemplateIndexViewModel();
            model.Templates = _flowTemplateService.GetFlowTemplates();
            return View(model);
        }

        [HttpGet]
        public ActionResult Add()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Add(Dto.FlowTemplateDto templateDto)
        {
            var flowTemplate = Mapper.Map<Library.Core.FlowTemplate>(templateDto);
            var id = _flowTemplateService.Add(flowTemplate);
            return RedirectToAction("Index", "FlowTemplateController", new {Success = true, Id = id});
        }

    }
}

Web/Web/Views/FlowTemplates/Add.cshtml
@model Flow.Web.Models.FlowTemplateAddModel
@{
    ViewBag.Title = "Add";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Add Flow Template</h2>
@using (var form = @Html.BeginForm("Add", "FlowTemplates"))
{
    @Html.ValidationSummary(false)
    <p>
        @Html.LabelFor(o => o.Name)
        @Html.TextBoxFor(o => o.Name)
    </p>
    <p>
        <input type="submit" value="Add" />
    </p>
}

Web/Web/Views/FlowTemplates/Index.cshtml
@{
    ViewBag.Title = "Listing all Flow Templates";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Flow Templates</h2>
<script src="~/Scripts/jquery-1.7.1.min.js"></script>
<script src="~/Scripts/knockout-2.1.0.js"></script>
<script src="~/Scripts/flow.Models.js"></script>
<script src="~/Scripts/jquery.pubsub.js"></script>

<ul class="template-list" data-bind="foreach:Templates">
    <li>
        <span><button type="button" class="delete-template-button" name="deleteTemplateButton" value="Delete" data-bind="click: Delete">Delete</button></span>
        <span data-bind="text: Id">Id</span>
        <span data-bind="text: Name">Name</span>
    </li>
</ul>

<div id="template-add-form">
    <p>
        Name: <br /> <input type="text" value="" name="Name" />
    </p>
    <p>
        <input type="submit" name="submit" value="Add FlowTemplate" />
    </p>
</div>

<script type="text/javascript">
    
    var flowTemplateActions = {
        
        get : function () {
            console.log("Fetching FlowTemplates for the first time");
            $.ajax("/api/FlowTemplates").done(function (data) {
                data.forEach(function (e) {
                   $.publish("flowtemplate.added", new FlowTemplateModel($, e));
                });
            }).fail(function () {
                console.log("Unable to get FlowTemplates");
                throw "Unable to get FlowTemplates";
            });
        },

        add : function (template) {

            var jsonData = ko.toJSON(template);
            $.ajax({
                url: "/api/FlowTemplates/" + template.Id(),
                data: jsonData,
                type: "POST",
                contentType: "application/json"
            }).success(function (resultData) {
                template.Id(resultData.Id);
                $.publish("flowtemplate.added", template);
            }).error(function () {
                console.log("Unable to update template " + template.Id);
                throw "Unable to update template";
            });
        },

        update : function (template) {

            var data = ko.toJSON(template);
            $.ajax({
                url: "/api/FlowTemplates/" + template.Id,
                data: data,
                type: "PUT",
                contentType: "application/json"
            }).success(function () {
                $.publish("flowtemplate.updated", template);
            }).error(function (err) {
                console.log("Unable to update template " + template.Id);
                console.log(err);
                throw err;
            });
        },

        remove : function (template) {
            $.ajax({
                url: "/api/FlowTemplates/" + template.Id(),
                type: "DELETE",
            }).success(function () {
                $.publish("flowtemplate.deleted", template);
            }).error(function (err) {
                console.log("Unable to delete template " + template.Id());
                console.log(err);
                throw err;
            });
        }
    }

</script>

<script type="text/javascript">

    var pageModel = new FlowTemplateIndexModel();

    $(document).ready(function () {

        ko.applyBindings(pageModel, document.getElementsByClassName("template-list")[0]);

        flowTemplateActions.get();

        $("#template-add-form input[type=submit]").click(function () {
            var newItem = new FlowTemplateModel($);
            newItem.Name = $(this).parent().siblings().find("input[name=Name]").val();
            $.publish("flowtemplate.add", newItem);
        });

        $.subscribe("flowtemplate.add", function (e, flowTemplate) {
            flowTemplateActions.add(flowTemplate);
        });

        $.subscribe("flowtemplate.added", function (e, flowTemplate) {
            pageModel.Templates.push(flowTemplate);
        });

        $.subscribe("flowtemplate.delete", function (e, flowTemplate) {
            var result = flowTemplateActions.remove(flowTemplate);
            if (result) {
                $.publish("flowtemplate.deleted", flowTemplate);
            }
        });

        $.subscribe("flowtemplate.deleted", function (e, flowTemplate) {
            for (var i = 0; i < pageModel.Templates().length; i++) {
                if (pageModel.Templates()[i].Id() == flowTemplate.Id()) {
                    pageModel.Templates.remove(pageModel.Templates()[i]);
                }
            }
        });

    });
</script>